### PR TITLE
HashSet: Add Semigroup instance

### PR DESCRIPTION
**Pull request by bgamari**
This will be necessary under GHC 8.4.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
This is a duplicate of #168, no?

**Comment by treeowl** [comment]
I was planning to merge #168 as soon as enough dependencies were worked out
for it to build on Travis, but if y'all prefer I can merge it now and take
the dependency updates as a separate PR.

On Sep 13, 2017 7:37 PM, "Ryan Scott" <notifications@github.com> wrote:

This is a duplicate of #168
<https://github.com/tibbe/unordered-containers/pull/168>, no?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tibbe/unordered-containers/pull/169#issuecomment-329326927>,
or mute the thread

**Comment by RyanGlScott** [comment]
Ah. It's a bit of a complicated story... The changes needed to fix `primitive` have landed, but I'm not sure if we'd want to make a Hackage release of it so soon, since there are still some other SMP-related changes that have yet to land in GHC HEAD.

**Comment by bgamari** [comment]
Closing in favor of #168.

**Pull request closed without merging**
